<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>9</LangVersion>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DICS.Generator\DICS.Generator.csproj" OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\DICS\DICS.csproj"/>
    </ItemGroup>
</Project>
